
domain: deannarothwell.com
url: https://deannarothwell.com
baseurl: #/deannaweb

title: "Deanna Rothwell"
title_separator: "!"

name: &name "Deanna Rothwell"
description: &description "put description here"

remote_theme: academicpages/academicpages.github.io
site_theme: default # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-remote-theme

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

author:
  avatar: profile.jpg
  name: Deanna Rothwell
  bio: Director of Analytics at The Ottawa Hospital. Senior Investigator, Methodological and Implementation Research at The Ottawa Hospital Research Institute
  location: Ottawa, Canada
  employer: The Ottawa Hospital
  uri: https://ohri.ca/en/find-researcher/deanna-rothwell
  email: drothwell@ohri.ca

  # academic sites
  orcid: https://orcid.org/0009-0002-9692-1471
  pubmed: https://pubmed.ncbi.nlm.nih.gov/?term=deanna+rothwell
  researchgate: https://www.researchgate.net/profile/Deanna-Rothwell

  # social media
  linkedin: deanna-rothwell-52a50133

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: false

collections:
  talks:
    output: true
    permalink: /:collection/:path/

analytics:
  provider: "google-analytics-4"
  google:
    tracking_id: "G-GSKE7NJV01"

